Updating bitrise.yml

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -10,9 +10,34 @@ trigger_map:
 workflows:
   primary:
     steps:
-    - activate-ssh-key@4:
-        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
     - git-clone@4: {}
     - script@1:
-        title: Do anything with Script step
+        title: Install Homebrew taps
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails; debug log
+
+            set -ex
+
+            # Install brew taps
+
+            brew tap yonaskolb/SwagGen https://github.com/yonaskolb/SwagGen.git
+    - script@1:
+        deps:
+          brew:
+          - name: SwagGen
+        inputs:
+        - content: >-
+            #!/usr/bin/env bash
+            # fail if any commands fails; debug log
+
+            set -ex
+
+            curl "https://converter.swagger.io/api/convert?url=https://api-docs.bitrise.io/docs/swagger.json" -H "Accept: application/json" -o ./openapi.json
+
+            swaggen generate openapi.json -d Sources/BitriseCLI -c all -t templates/CLI/template.yml -o "name:BitriseCLI" -o "commandProtocol:AuthenticatedCommand"
+
+            swift build --product br
+        title: SwagGen
     - deploy-to-bitrise-io@1: {}
